### ISSUE TITLE
Remove Conflicts

### ISSUE THREAD

**Issue by DeathStroke19891** [KTS-o7/Compiler-Design#6]
Some of the later programs have shift-reduce and reduce-reduce conflicts which will not be accepted in the Practical exams. So the grammars need to be modified in a way that they don't produce conflicts or ambiguity.

**Comment by KTS-o7** [comment]
> Some of the later programs has shift-reduce and reduce-reduce conflicts which will not be accepted in the Practical exams. So the grammars need to be modified in a way that they don't produce conflicts or ambiguity.

@DeathStroke19891 How do you suggest removing the conflicts?

Is there any specific way to change the grammar so that conflicts are avoided ?

**Comment by DeathStroke19891** [comment]
We might need to add precedence and associativity rules to remove the ambiguity or rewrite the grammar entirely. I will try opening a PR for the same by tonight

**Comment by KTS-o7** [comment]
Yeah check it out
It has to do something like 
%pred
%left
%right etc

**Comment by KTS-o7** [comment]
Resolved with #7
